name: Build and Publish GT Frontend

on:
  push:
    branches:
      - main
      - dev

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use Node 16.16.0 LTS
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.0

      - name: Install NPM packages
        run: npm install

      - name: Build the React Application
        run: CI=false npm run build --if-present

      - name: Compress the Build
        run: zip -r gt-frontend-build.zip build

      - name: Publish the Release to GitHub Releases
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: gt-frontend-build.zip
          title: GT Frontend v1.0.0
          automatic_release_tag: v1.0.0

#Not Working as expected
#      - name: Publish the Release to GitHub Releases
#        uses: softprops/action-gh-release@v1
#        with:
#          target_commitish: ${{ GITHUB.SHA }}
#          files: gt-frontend-build.zip
#          name: GT Frontend v1.0.0
#          tag_name: v1.0.0
#          generate_release_notes: true


